Code Refactoring and ReOrganization
buddypress/bp-blocks pull request #16
Opened 2020-09-12 14:23 UTC by renatonascalves

There are several changes here and sorry for going a bit overboard.

Mainly I'm suggesting a "better" organization and trying to bring some code changes to improve documentation, reading, and understanding of the codebase.

Let me know what you think.

2020-09-12 17:25 UTC, imath requested changes
Hi @renatonascalves 

Thanks a lot for your work on this. Unfortunately I can't approve it. I agree code organization is really nice, but we need to make sure there are no feature regressions. There's at least one I've found that made me stopped my tests of your PR:

When publishing an activity, the Publish button should animate itself, the content of editor should be cleared and a notice should allow me to view the just posted activity.

See this video for the expected behavior: [video](https://cldup.com/tN_FKQaoD5.mp4)

I would advise you to test the Editor, the block to share a post into the activity stream and the one to embed an activity using the master branch to be sure your edits do not generate regressions about the features 😉 

Also, JavaScript indentation style is wrong. As [WordPress JavaScript Coding standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/) requires: `tab` must be used instead of 2 spaces.

2020-09-12 18:54 UTC, renatonascalves commented
@imath Awesome! I was expecting more push back from those changes, but I'm happy when you are open to that.

I'm going to address those issues and request another review when ready. =D

2020-09-12 20:21 UTC, renatonascalves commented on build/bp-activity/bp-activity-blocks.php
> +			'style'               => array(),
I changed this into an `array` since this is what's expected and it was causing `undefined` errors.

2020-09-12 20:23 UTC, renatonascalves commented
@imath Updated to account for:

- the indentation issues: we are using tabs now
- the correct actions are being fired when saving the activity

I tested the blocks and the activity editor and they seem to be working as expected now.

:)

2020-09-13 11:45 UTC, imath approved these changes
I confirm it fixed the regression. Thanks a lot for your great work on this PR @renatonascalves. I agree your reorganization is really nice. Let's have it in!

2020-09-13 11:45 UTC, merged